language: java

cache:
  directories:
    - $HOME/.m2

jdk:
  - openjdk5
  - oraclejdk5
  - openjdk6
  - oraclejdk6
  - openjdk7
  - oraclejdk7
  - openjdk8
  - oraclejdk8
  - oraclejdk9

script:
  - mvn clean test
